package ramo.klevis.test.bindingform;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class BeanView extends CustomComponent {


	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TextField ageField;
	@AutoGenerated
	private TextField surnameField;
	@AutoGenerated
	private TextField nameField;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public BeanView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("320px");
		mainLayout.setHeight("220px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("320px");
		setHeight("220px");
		
		// nameField
		nameField = new TextField();
		nameField.setCaption("Person name");
		nameField.setImmediate(false);
		nameField.setWidth("-1px");
		nameField.setHeight("-1px");
		nameField.setSecret(false);
		mainLayout.addComponent(nameField);
		
		// surnameField
		surnameField = new TextField();
		surnameField.setCaption("Person surname");
		surnameField.setImmediate(false);
		surnameField.setWidth("-1px");
		surnameField.setHeight("-1px");
		surnameField.setSecret(false);
		mainLayout.addComponent(surnameField);
		
		// ageField
		ageField = new TextField();
		ageField.setCaption("Person age");
		ageField.setImmediate(false);
		ageField.setWidth("-1px");
		ageField.setHeight("-1px");
		ageField.setSecret(false);
		mainLayout.addComponent(ageField);
		
		return mainLayout;
	}

}
